"use client";
import { useState } from "react";
import type { Asset, Effect, EffectAction } from "@streamfx/types";
import { Check, Field, Icon, number, text } from "./studio-ui";
export const actionNames: Record<EffectAction["type"], string> = { image: "Hình ảnh", video: "Video", audio: "Âm thanh", confetti: "Pháo giấy", wait: "Chờ", clear: "Xóa toàn bộ", stop: "Dừng hiện tại" };
export function assetUrl(asset: Asset & { path?: string }) { return asset.url || (asset.path ? `/assets/${encodeURIComponent(asset.path.split(/[\\/]/).pop()!)}` : ""); }
export default function EffectEditor({ effect, assets, busy, save, cancel }: { effect?: Effect; assets: Asset[]; busy: boolean; save: (body: unknown) => void; cancel: () => void }) {
  const [actions, setActions] = useState<EffectAction[]>(effect?.actions ?? [{ type: "confetti", durationMs: 3000 }]);
  function update(index: number, patch: Partial<EffectAction>) { setActions(current => current.map((action, i) => i === index ? { ...action, ...patch } : action)); }
  function move(index: number, offset: number) { setActions(current => { const copy = [...current]; [copy[index], copy[index + offset]] = [copy[index + offset], copy[index]]; return copy; }); }
  return <form className="panel editor" onSubmit={event => { event.preventDefault(); const values = new FormData(event.currentTarget); save({ name: text(values, "name"), mode: text(values, "mode"), cooldownMs: number(values, "cooldownMs"), enabled: values.has("enabled"), actions }); }}>
    <h3>{effect ? "Sửa hiệu ứng" : "Hiệu ứng mới"}</h3><fieldset disabled={busy}><div className="form-grid"><Field label="Tên hiệu ứng"><input name="name" required maxLength={80} defaultValue={effect?.name} /></Field><Field label="Khi đang phát"><select name="mode" defaultValue={effect?.mode ?? "QUEUE"}><option value="QUEUE">Xếp hàng</option><option value="REPLACE">Thay thế hiện tại</option><option value="DROP">Bỏ lượt mới khi bận</option></select></Field><Field label="Thời gian hồi (ms)"><input type="number" name="cooldownMs" min={0} max={3600000} defaultValue={effect?.cooldownMs ?? 0} required /></Field><Check name="enabled" label="Bật hiệu ứng" checked={effect?.enabled ?? true} /></div>
    <header className="section-head"><h3>Chuỗi hành động <small>{actions.length}/20</small></h3><button type="button" className="ghost compact" disabled={actions.length >= 20} onClick={() => setActions([...actions, { type: "wait", durationMs: 1000 }])}><Icon name="plus" />Hành động</button></header>
    <div className="action-list">{actions.map((action, index) => <section className="action-row" key={index}><header className="section-head"><strong>Bước {index + 1}</strong><div className="actions"><button type="button" className="ghost compact" aria-label={`Đưa bước ${index + 1} lên`} disabled={index === 0} onClick={() => move(index, -1)}><Icon name="back" style={{ transform: "rotate(90deg)" }} /></button><button type="button" className="ghost compact" aria-label={`Đưa bước ${index + 1} xuống`} disabled={index === actions.length - 1} onClick={() => move(index, 1)}><Icon name="back" style={{ transform: "rotate(-90deg)" }} /></button><button type="button" className="danger compact" disabled={actions.length === 1} onClick={() => setActions(actions.filter((_, i) => i !== index))}><Icon name="trash" />Bỏ bước</button></div></header><div className="form-grid">
      <Field label="Loại"><select value={action.type} onChange={event => { const type = event.target.value as EffectAction["type"]; setActions(actions.map((a, i) => i === index ? { type, durationMs: type === "clear" || type === "stop" ? 0 : 3000, ...(["image", "video", "audio"].includes(type) ? { url: "" } : {}) } : a)); }}>{Object.entries(actionNames).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
      <Field label="Thời lượng (ms)"><input type="number" required min={["wait", "stop", "clear"].includes(action.type) ? 0 : 100} max={300000} value={action.durationMs} onChange={event => update(index, { durationMs: Number(event.target.value) })} /></Field>
      {["image", "video", "audio"].includes(action.type) && <><Field label="Chọn từ thư viện"><select value={assets.some(asset => assetUrl(asset) === action.url) ? action.url : ""} onChange={event => update(index, { url: event.target.value })}><option value="">Chọn tệp hoặc nhập URL bên dưới</option>{assets.filter(asset => asset.mime.startsWith(`${action.type}/`)).map(asset => <option key={asset.id} value={assetUrl(asset)}>{asset.name}</option>)}</select></Field><Field label="URL tệp" hint="Đường dẫn /assets/… hoặc URL HTTP(S)."><input required value={action.url ?? ""} pattern="(https?://|/).*" onChange={event => update(index, { url: event.target.value })} /></Field></>}
      {["audio", "video", "image"].includes(action.type) && <Field label="Âm lượng (0–1)"><input type="number" min={0} max={1} step={0.05} required value={action.volume ?? 1} onChange={event => update(index, { volume: Number(event.target.value) })} /></Field>}
    </div>{["clear", "stop"].includes(action.type) && <p className="muted">Hành động này điều khiển phát trên overlay khi hiệu ứng chạy.</p>}</section>)}</div>
    <div className="actions form-footer"><button type="submit">{busy ? "Đang lưu…" : <><Icon name="check" />Lưu hiệu ứng</>}</button><button type="button" className="ghost" onClick={cancel}>Hủy</button></div></fieldset>
  </form>;
}
